### ISSUE TITLE
Running FLUTE from main.py on macOS

### ISSUE THREAD

**Issue by JoachimGoedhart** [LaboratoryOpticsBiosciences/FLUTE#4]
I had to go through quite some steps before I was able to run **FLUTE** from `main.py`. The main issue was to install PyQt5. This stackoverflow post (and the MacOS specific answer) was of great help:
[https://stackoverflow.com/questions/70961915/error-while-installing-pytq5-with-pip-preparing-metadata-pyproject-toml-did-n](https://stackoverflow.com/questions/70961915/error-while-installing-pytq5-with-pip-preparing-metadata-pyproject-toml-did-n)
I document the steps here as detailed as possible, as it may be helpful for others.

I'm on macOS Montery (12.4) with a MacBook Pro (14-inch, 2021), Apple M1 pro chip and I'm using the miniconda distribution of Python.

-----------------

## First, in the terminal install brew:

`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
`

After installation, there will be instructions from brew, which I followed. These are copied below:

`(echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> /Users/joachimgoedhart/.zprofile
`
`eval "$(/opt/homebrew/bin/brew shellenv)"
`

## Second, use brew to install qt5:

`brew install qt5`

Next we need to find the place where bin/qmake is located. On my laptop it is:

`/opt/homebrew/opt/qt@5/bin
`

Now I add to the file (located in my homefolder): `.zshrc`

This line of code:

`export PATH="$PATH:/opt/homebrew/opt/qt@5/bin"
`

## Third, I was able to install PyQt5:

`pip install pyqt5 --config-settings --confirm-license= --verbose
`
This worked (took quite some time to compile)!!!

----------------------

After these steps I was able to install the packages in a new environment:

- `pip install numpy`
- `pip install PyQt5`
- `pip install opencv-python`
- `pip install pip install`
- `pip install matplotlib==3.6.3`

And tada, I was able to run:

`python main.py`

**Comment by polykko** [comment]
Dear Joachim,

I have a Mac with the same specifications and I have encountered the same problem. There is another solution with more steps, but way more user-friendly than working through the terminal:

1. Install Anaconda Navigator, which is a GUI to manage Python environments and libraries. The documentation is available here: [https://docs.anaconda.com/free/navigator/index.html](https://docs.anaconda.com/free/navigator/index.html)

![](https://docs.anaconda.com/_images/nav-tabs.png)

2. Go to the Environments tab and create a new environment for running FLUTE. It is not mandatory, but much recommended, because it will help you to avoid library dependencies in case if you use Python to run other programs.

3. In the same Environments tab with the FLUTE environment activated, on the top right corner you can  search and install specific versions of libraries. To make PyQt5 running, you need to install `qtpy` and `pyqt` (as I had exactly the same issue and it helped). Also, please make sure that your `matplotlib` version is **3.6.2** or **3.6.3** as otherwise it could cause compatibility issues.

4. Install PyCharm Community edition (either from Anaconda homepage or online), then upon startup you can just insert a link to the FLUTE’s GitHub and all necessary files will download automatically. Then go to Preferences -> Project: main.py -> Python Interpreter, and select Anaconda environment you've created.

5. Now you can run `main.py` and it should work! I tried to run it with Spyder and it was occasionally giving some errors, so I would recommend sticking to PyCharm.

I hope this resolves the problem and proves to be useful. Please let me know if you have tried it and whether it worked for you, as well as if you have any other questions.

**Comment by ChiaraStringari** [comment]
Hi Joachim and Polina! 
Thanks for sharing your steps with MacOS to install PyQt5 and run FLUTE from main.py.
I think it will be useful for many people.

Concerning the packages dependencies we fixed the issue with matplotlib, so the newest version works with any version of matplotlib.
You can therefore install "pip install matplotlib"
(don't need to install 3.6.3 version).

**Comment by JoachimGoedhart** [comment]
Thanks! I can confirm that the FLUTE GUI runs with the most recent matplotlib, which was 3.7.1 for me.
